name: BACKUP_RESTORE

env:
########################## USER DETAILS ################################
  wip: 'projects/13793097680/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
  sa: 'my-service-account@grand-thought-365806.iam.gserviceaccount.com'
#########################################################################

########################### PROJECT DETAILS ################################
  project_id: 'grand-thought-365806'    
  gke_project_id: "np-homeservices"
############################################################################ 

############################### ZONE INFO ################################## 
  zone_us_east: us-east1-b
  zone_us_west: us-west1-c
############################################################################

#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> US WEST CLUSTER INFO <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

########################### US WEST DATABASE INFO ########################## 

  geodb_us_west: geodb
  notifydb_us_west: notifydb
  securitydb_dr_us_west: securitydb-dr
  serviceproviderdb_dr_us_west: serviceproviderdb-dr
  tresurydb_dr_us_west: tresurydb-dr
  workorderdb_dr_us_west: workorderdb-dr
  servicecatalogdb_dr_us_west: servicecatalogdb-dr

############################################################################ 

########################## US WEST LOAD BALANCER INFO ###################### 

  us_west_external_lb_backend_service_name: thd-dev-backend-svc1
  us_west_external_lb_url_map: test-lb
  us_west_internal_lb_backend_service_name: thd-dev-backend-svc1-internal
  us_west_internal_lb_url_map: thd-dev-url-map-internal

############################################################################

####################### US WEST : BACKUP RELATED INFO #######################   

  backup_name_us_west_to_us_east: "thd-us-west-to-us-east-backup"
  restore_name_us_west_to_us_east: "thd-us-west-to-us-east-restore"
  backup_plan_us_west_to_us_east: "thd-us-west-to-us-east-backup-plan"
  restore_plan_us_west_to_us_east: "thd-us-west-to-us-east-restore-plan" 

##############################################################################    

#<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> 

#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> US EAST CLUSTER INFO <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

########################## US EAST LOAD BALANCER INFO ###################### 

  us_east_external_lb_backend_service_name: thd-dev-backend-svc2
  us_east_external_lb_url_map: test-lb
  us_east_internal_lb_backend_service_name: thd-dev-backend-svc2-internal
  us_east_internal_lb_url_map: thd-dev-url-map-internal

############################################################################ 

########################## US EAST DATABASE INFO ###########################

  geodb_us_east: geodb-replica
  notifydb_us_east: notifydb-replica
  securitydb_dr_us_east: securitydb-dr-replica
  serviceproviderdb_dr_us_east: serviceproviderdb-dr-replica
  tresurydb_dr_us_east: tresurydb-dr-replica
  workorderdb_dr_us_east: workorderdb-dr-replica
  servicecatalogdb_dr_us_east: servicecatalogdb-dr-replica

########################################################################### 

####################### US EAST : BACKUP RELATED INFO #######################   

  backup_name_us_east_to_us_west: "thd-us-east-to-us-west-backup"
  restore_name_us_east_to_us_west: "thd-us-east-to-us-west-restore"
  backup_plan_us_east_to_us_west: "thd-us-east-to-us-west-backup-plan"
  restore_plan_us_east_to_us_west: "thd-us-east-to-us-west-restore-plan"

##############################################################################  

#<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>># 

on:
  workflow_dispatch:
    inputs:
      switch_to_region:
        type: choice
        description: Select the region you would like to switch To
        options: 
        - us-west1-a 
        - us-east1-b 
      gke_backup_restore: 
        type: choice
        description: Would you like to create a backup before restore (Selecte False, if you would like to restore from existing backup)
        options:
          - Yes
          - No
 
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # LB_REBASE_US_EAST:
  #   permissions:
  #     contents: 'read'
  #     id-token: 'write'
  #   runs-on: ubuntu-latest
  #   if: contains(inputs.switch_to_region, 'us-east1-b')
  #   steps:
  #     - name: Set up gcloud Cloud SDK environment
  #       uses: 'google-github-actions/auth@v0'
  #       with:
  #         workload_identity_provider: 'projects/13793097680/locations/global/workloadIdentityPools/github-dr-pool/providers/github-dr-provider'
  #         service_account: 'github-test-dr@grand-thought-365806.iam.gserviceaccount.com'
  #     - name: 'Set up Cloud SDK'
  #       uses: 'google-github-actions/setup-gcloud@v0'
  #     - name: 'Use gcloud CLI'
  #       run: |
  #         gcloud info
  #         gcloud version
  #         gcloud compute url-maps list
  #         gcloud compute url-maps set-default-service --default-service=$us_east_external_lb_backend_service_name $us_east_external_lb_url_map --project="$project_id"
  #         # gcloud compute url-maps set-default-service --default-service=$us_east_internal_lb_backend_service_name $us_east_internal_lb_url_map --project="$project_id"
        
  # LB_REBASE_US_WEST:
  #   permissions:
  #     contents: 'read'
  #     id-token: 'write'
  #   runs-on: ubuntu-latest
  #   if: contains(inputs.switch_to_region, 'us-west1-a')
  #   steps:
  #     - name: Set up gcloud Cloud SDK environment
  #       uses: 'google-github-actions/auth@v0'
  #       with:
  #         workload_identity_provider: 'projects/13793097680/locations/global/workloadIdentityPools/github-dr-pool/providers/github-dr-provider'
  #         service_account: 'github-test-dr@grand-thought-365806.iam.gserviceaccount.com'
  #     - name: 'Set up Cloud SDK'
  #       uses: 'google-github-actions/setup-gcloud@v0'
  #     - name: 'Use gcloud CLI'
  #       run: |
  #         gcloud info
  #         gcloud version
  #         gcloud compute url-maps set-default-service --default-service=$us_west_external_lb_backend_service_name $us_west_external_lb_url_map --project="$project_id"
  #         # gcloud compute url-maps set-default-service --default-service=$us_west_internal_lb_backend_service_name $us_west_internal_lb_url_map --project="$project_id"
  
  GKE_BACKUP_RESTORE_US_WEST_To_US_EAST:
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: "homeservices"
    if: contains(inputs.switch_to_region, 'us-east')
    steps:
      - name: Set up gcloud Cloud SDK environment
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: 'projects/13793097680/locations/global/workloadIdentityPools/github-dr-pool/providers/github-dr-provider'
          service_account: 'github-test-dr@grand-thought-365806.iam.gserviceaccount.com'
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
      - name: 'Use gcloud CLI'
        run: |
          gcloud info
          gcloud version
          gcloud components install beta
          echo "================================beta component installed ========================================"
          # logic to create backup and restore 
          dt=$(date +%m-%d-%y)
          backup_name_us_west_to_us_east="$backup_name_us_west_to_us_east-$dt"
          restore_name_us_west_to_us_east="$restore_name_us_west_to_us_east-$dt"
          echo "The backup name is: $backup_name_us_west_to_us_east"
          echo "The restore name is: $restore_name_us_west_to_us_east"
          echo " ${{ github.event.inputs.gke_backup_restore }}"
          if [ ${{ github.event.inputs.gke_backup_restore }} == "true" ]
          then 
            # Create backup \
            echo "In if Loop us-east"
            gcloud beta container backup-restore backups create $backup_name_us_west_to_us_east \
                --project=$gke_project_id \
                --location=us-east1  \
                --backup-plan=$backup_plan_us_west_to_us_east \
                --wait-for-completion
            # Restore Backup
            gcloud beta container backup-restore restores create $restore_name_us_west_to_us_east \
              --project=$gke_project_id \
              --location=us-east1  \
              --restore-plan=$restore_plan_us_west_to_us_east \
              --backup="projects/$gke_project_id/locations/us-east1/backupPlans/$backup_plan_us_west_to_us_east/backups/$backup_name_us_west_to_us_east" \
              --wait-for-completion
          else 
            # Only Restore logic 
            echo "In else Loop us-east"
            # Restore Backup 
            backup_name_us_west_to_us_east=$(gcloud beta container backup-restore backups list --backup-plan=$backup_plan_us_west_to_us_east --project=$gke_project_id --location=us-east1 --sort-by='~' | awk 'NR==2,/NAME: /{print $1}') 
            echo "The latest backup file name as per search history is : $backup_name_us_west_to_us_east"
            echo "projects/$gke_project_id/locations/us-west1/backupPlans/$backup_plan_us_west_to_us_east/backups/$backup_name_us_west_to_us_east"
            gcloud beta container backup-restore restores create $restore_name_us_west_to_us_east \
              --project=$gke_project_id \
              --location=us-east1  \
              --restore-plan=$restore_plan_us_west_to_us_east \
              --backup=projects/$gke_project_id/locations/us-east1/backupPlans/$backup_plan_us_west_to_us_east/backups/$backup_name_us_west_to_us_east \
              --wait-for-completion
          fi

  GKE_BACKUP_RESTORE_US_EAST_To_US_WEST:
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: "homeservices"
    if: contains(inputs.switch_to_region, 'us-west1-c')
    steps:
      - name: Set up gcloud Cloud SDK environment
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: 'projects/13793097680/locations/global/workloadIdentityPools/github-dr-pool/providers/github-dr-provider'
          service_account: 'github-test-dr@grand-thought-365806.iam.gserviceaccount.com'
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
      - name: 'Use gcloud CLI'
        run: |
          gcloud info
          gcloud version
          gcloud components install beta
          echo "================================ Beta Component Installed ========================================"
          # logic to create backup and restore 
          dt=$(date +%m-%d-%y)
          backup_name_us_east_to_us_west="$backup_name_us_east_to_us_west-$dt"
          restore_name_us_east_to_us_west="$restore_name_us_east_to_us_west-$dt"
          echo "The backup name is: $backup_name_us_east_to_us_west"
          echo "The restore name is: $restore_name_us_east_to_us_west"
          if [ ${{ github.event.inputs.gke_backup_restore }} == "true" ]
          then 
            # Create backup 
            echo "In if Loop us-west"
            gcloud beta container backup-restore backups create $backup_name_us_east_to_us_west \
              --project=$gke_project_id \
              --location=us-west1 \
              --backup-plan=$backup_plan_us_east_to_us_west \
              --wait-for-completion
            # Restore Backup
            gcloud beta container backup-restore restores create $restore_name_us_east_to_us_west \
              --project=$gke_project_id \
              --location=us-west1 \
              --restore-plan=$restore_plan_us_east_to_us_west \
              --backup="projects/$gke_project_id/locations/us-west1/backupPlans/$backup_plan_us_east_to_us_west/backups/$backup_name_us_east_to_us_west" \
              --wait-for-completion
          else 
            # Only Restore logic 
            echo "In else Loop us-west"
            # Restore Backup 
            backup_name_us_east_to_us_west=$(gcloud beta container backup-restore backups list --backup-plan=$backup_plan_us_west_to_us_west --project=$gke_project_id --location=us-east1 --sort-by='~' | awk 'NR==2,/NAME: /{print $1}') 
            echo "The latest backup file name as per search history is : $backup_name_us_east_to_us_west"
            echo "projects/$gke_project_id/locations/us-west1/backupPlans/$restore_plan_us_east_to_us_west/backups/$backup_name_us_east_to_us_west"
            gcloud beta container backup-restore restores create $restore_name_us_east_to_us_west \
              --project=$gke_project_id \
              --location=us-west1 \
              --restore-plan=$restore_plan_us_east_to_us_west \
              --backup="projects/$gke_project_id/locations/us-west1/backupPlans/$backup_plan_us_east_to_us_west/backups/$backup_name_us_east_to_us_west" \
              --wait-for-completion
          fi
