name: New-DR-Trigger

env:
########################## USER DETAILS ################################
  wip: 'projects/13793097680/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
  sa: 'my-service-account@grand-thought-365806.iam.gserviceaccount.com'
#########################################################################

########################### PROJECT DETAILS ################################
  project_id: 'grand-thought-365806'    
  gke_project_id: 'grand-thought-365806'
############################################################################ 

############################### ZONE INFO ################################## 
  zone_secondary: us-west1-a
  zone_primary: us-central1-b
############################################################################

#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> Primary CLUSTER INFO <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

########################### Primary DATABASE INFO ########################## 

  geodb_primary: db-us-central
  notifydb_primary: notifydb
  securitydb_dr_primary: securitydb-dr
  serviceproviderdb_dr_primary: serviceproviderdb-dr
  tresurydb_dr_primary: tresurydb-dr
  workorderdb_dr_primary: workorderdb-dr
  servicecatalogdb_dr_primary: servicecatalogdb-dr

############################################################################ 

########################## Primary LOAD BALANCER INFO ###################### 

  primary_external_lb_backend_service_name: thd-dev-backend-svc2
  primary_external_lb_url_map: thd-global
  primary_internal_lb_backend_service_name: thd-dev-backend-svc1-internal
  primary_internal_lb_url_map: thd-dev-url-map-internal

############################################################################

####################### Primary : BACKUP RELATED INFO #######################   

  backup_name_primary_to_secondary: "thd-us-central-to-us-west-backup"
  restore_name_primary_to_secondary: "thd-us-central-to-us-west-restore"
  backup_plan_primary_to_secondary: "thd-us-central-to-us-west-backup-plan"
  restore_plan_primary: "thd-us-central-restore-plan" 

##############################################################################    

#<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> 

#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> Secondary CLUSTER INFO <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

########################## Secondary LOAD BALANCER INFO ###################### 

  secondary_external_lb_backend_service_name: thd-dev-backend-svc1
  secondary_external_lb_url_map: thd-global
  secondary_internal_lb_backend_service_name: thd-dev-backend-svc2-internal
  secondary_internal_lb_url_map: thd-dev-url-map-internal

############################################################################ 

########################## Secondary DATABASE INFO ###########################

  geodb_secondary: db-us-west
  notifydb_secondary: notifydb-replica
  securitydb_dr_secondary: securitydb-dr-replica
  serviceproviderdb_dr_secondary: serviceproviderdb-dr-replica
  tresurydb_dr_secondary: tresurydb-dr-replica
  workorderdb_dr_secondary: workorderdb-dr-replica
  servicecatalogdb_dr_secondary: servicecatalogdb-dr-replica

########################################################################### 

####################### Secondary : BACKUP RELATED INFO #######################   

  backup_name_secondary_to_primary: "thd-us-west-to-us-central-backup"
  restore_name_secondary_to_primary: "thd-us-west-to-us-central-restore"
  backup_plan_secondary_to_primary: "thd-us-west-to-us-central-backup-plan"
  restore_plan_secondary: "thd-us-west-restore-plan"
  

##############################################################################  

#<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>># 

on:
  workflow_dispatch:
    inputs:
      switch_to_region:
        type: choice
        description: Select the region you would like to switch To
        options: 
        - us-west
        - us-central
      gke_backup_restore: 
        type: choice
        description: Would you like to create a backup before restore (Selecte False, if you would like to restore from existing backup)
        options:
          - Yes
          - No
 
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  SCALE_DEPLOYMENTS_PRIMARY:
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    if: contains(inputs.switch_to_region, 'us-central')
    steps:
      - name: Set up gcloud Cloud SDK environment
        uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: 'projects/13793097680/locations/global/workloadIdentityPools/github-dr-pool/providers/github-dr-provider'
          service_account: 'github-test-dr@grand-thought-365806.iam.gserviceaccount.com'
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/get-gke-credentials@v1'
        with:
          cluster_name: 'us-central'
          location: 'us-central1-c'
      - name: "Scaling the deployments"
        run: |
          kubectl get nodes
