# This is a basic workflow to help you get started with Actions

name: TEST

# Controls when the workflow will run
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  all_dbs: (db-us-central, notifydb, securitydb-dr, serviceproviderdb-dr, tresurydb-dr, workorderdb-dr, servicecatalogdb-dr)
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          for db in env.all_dbs
          do 
            echo "db"
          done
