# This is a basic workflow to help you get started with Actions

name: TEST

# Controls when the workflow will run
on:


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      switch_to_region:
        type: choice
        description: Select the region you would like to switch To
        options: 
        - us-west
        - us-central
      gke_backup_restore: 
        type: choice
        description: Would you like to create a backup before restore (Selecte False, if you would like to restore from existing backup)
        options:
          - Yes
          - No
      rollback: 
        type: choice
        description: Would you like to rollback ?
        options:
          - Yes
          - No

jobs:
  build:
    runs-on: ubuntu-latest
    if: inputs.switch_to_region =='us-west' && inputs.rollback == 'true'
    steps:
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
